apiVersion: batch/v1
kind: Job
metadata:
  name: dynamodb-init
  namespace: tiny-url
  labels:
    app: dynamodb
    component: init
spec:
  template:
    metadata:
      labels:
        app: dynamodb
        component: init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-table
        image: amazon/aws-cli:latest
        command:
        - sh
        - -c
        - |
          echo "Creating DynamoDB table: url_mappings"
          aws dynamodb create-table \
            --table-name url_mappings \
            --attribute-definitions \
              AttributeName=short_code,AttributeType=S \
              AttributeName=creation_date,AttributeType=S \
            --key-schema \
              AttributeName=short_code,KeyType=HASH \
              AttributeName=creation_date,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST \
            --endpoint-url http://dynamodb-service:8000 \
            --region us-east-1 || echo "Table might already exist"

          echo "Verifying table creation..."
          aws dynamodb describe-table \
            --table-name url_mappings \
            --endpoint-url http://dynamodb-service:8000 \
            --region us-east-1

          echo "DynamoDB table initialization complete!"
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "dummy"
        - name: AWS_SECRET_ACCESS_KEY
          value: "dummy"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
