[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short --cov=src"

[tool.flake8]
max-line-length = 70
extend-ignore = ["E203"]
per-file-ignores = ["tests/*:D103"]
exclude = ["tests/"]
