[tool.black]
line-length = 70
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 70
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict_optional = true
disable_error_code = ["misc"] # Ignore untyped decorator errors
exclude = ["tests/"]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]         # Skip assert statements warning

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short --cov=src"

[tool.flake8]
max-line-length = 70
extend-ignore = ["E203"]
per-file-ignores = ["tests/*:D103"]
exclude = ["tests/"]
