apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten
  namespace: tiny-url
  labels:
    app: shorten
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shorten
  template:
    metadata:
      labels:
        app: shorten
        component: api
    spec:
      containers:
      - name: shorten
        image: tiny-url-shorten:local
        imagePullPolicy: Never  # Use local image, don't try to pull
        ports:
        - containerPort: 8000
          name: http
        # Load environment variables from ConfigMap
        envFrom:
        - configMapRef:
            name: shorten-config
        # Health checks (converted from docker-compose healthcheck)
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
