apiVersion: v1
kind: Service
metadata:
  name: shorten-service
  namespace: tiny-url
  labels:
    app: shorten
    component: api
spec:
  selector:
    app: shorten
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
