apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect
  namespace: tiny-url
  labels:
    app: redirect
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redirect
  template:
    metadata:
      labels:
        app: redirect
        component: api
    spec:
      containers:
      - name: redirect
        image: tiny-url-redirect:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
          name: http
        envFrom:
        - configMapRef:
            name: redirect-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
