apiVersion: v1
kind: Service
metadata:
  name: redirect-service
  namespace: tiny-url
  labels:
    app: redirect
    component: api
spec:
  selector:
    app: redirect
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  type: ClusterIP
