name: Run E2E Tests (Docker)

on:
  push:

jobs:
  e2e-test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services
      run: |
        make docker-build
        make docker-up

    - name: Wait for services to be ready
      run: |
        # Wait for DynamoDB Local
        echo "Waiting for DynamoDB Local..."
        timeout 60 bash -c 'until aws dynamodb list-tables --endpoint-url http://localhost:8002 > /dev/null 2>&1; do sleep 2; done'

        # Wait for shorten service
        echo "Waiting for shorten service..."
        timeout 60 bash -c 'until curl -f http://localhost:8000/health > /dev/null 2>&1; do sleep 2; done'

        # Wait for redirect service
        echo "Waiting for redirect service..."
        timeout 60 bash -c 'until curl -f http://localhost:8001/health > /dev/null 2>&1; do sleep 2; done'

    - name: Create DynamoDB table
      run: |
        aws dynamodb create-table \
          --table-name url_mappings \
          --attribute-definitions AttributeName=short_code,AttributeType=S \
          --key-schema AttributeName=short_code,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST \
          --endpoint-url http://localhost:8002 || true

    - name: Run E2E tests against Docker services
      run: |
        make e2e

    - name: Show service logs on failure
      if: failure()
      run: |
        echo "=== Shorten Service Logs ==="
        docker-compose logs shorten
        echo "=== Redirect Service Logs ==="
        docker-compose logs redirect
        echo "=== DynamoDB Local Logs ==="
        docker-compose logs dynamodb-local

    - name: Cleanup
      if: always()
      run: |
        make docker-down
