name: Run E2E Tests (Docker)

on:
  push:

jobs:
  e2e-test-docker:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup and start containerized services
      run: |
        make docker-setup

    - name: Run E2E tests against Docker services
      run: |
        make e2e

    - name: Show service logs on failure
      if: failure()
      run: |
        echo "=== Shorten Service Logs ==="
        docker compose logs shorten
        echo "=== Redirect Service Logs ==="
        docker compose logs redirect
        echo "=== DynamoDB Local Logs ==="
        docker compose logs dynamodb-local

    - name: Cleanup
      if: always()
      run: |
        make docker-down
